apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  replicas: 1
  selector:
    name: frontend
  template:
    metadata:
      labels:
        name: frontend
    spec:
      containers:
      - name: frontend
        image: luigimolinaro/go-rest:latest
        command: ["/bin/sh"]
        args: ["-c", "/opt/go-rest/go-rest"]
